language: python
python:
  - "3.8"
os:
  - linux
install:
  - pip install -r requirements.txt &> /dev/null
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py runserver