# Generated by Django 4.0.3 on 2022-03-27 12:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='kubeconfig',
            field=jsonfield.fields.JSONField(),
        ),
    ]
